const MatchState = Object.freeze({
  LOBBY: 'LOBBY',
  EM_JOGO: 'EM_JOGO',
  EMERGENCIA: 'EMERGENCIA',
  FINALIZADA: 'FINALIZADA',
});

const Role = Object.freeze({
  TRIPULANTE: 'TRIPULANTE',
  IMPOSTOR: 'IMPOSTOR',
});

const PlayerStatus = Object.freeze({
  VIVO: 'VIVO',
  MORTO: 'MORTO',
  DESCONECTADO: 'DESCONECTADO',
});

const EventType = Object.freeze({
  PLAYER_JOINED: 'PLAYER_JOINED',
  GAME_STARTED: 'GAME_STARTED',
  QR_SCANNED: 'QR_SCANNED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  PLAYER_REPORTED_DEAD: 'PLAYER_REPORTED_DEAD',
  SABOTAGE_TRIGGERED: 'SABOTAGE_TRIGGERED',
  SABOTAGE_RESOLVED: 'SABOTAGE_RESOLVED',
  EMERGENCY_CALLED: 'EMERGENCY_CALLED',
  EMERGENCY_CLEARED: 'EMERGENCY_CLEARED',
  GAME_ENDED: 'GAME_ENDED',
});

module.exports = {
  MatchState,
  Role,
  PlayerStatus,
  EventType,
};
